/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Cliente;

/**
 *
 * @author andre alves
 * @
 */
public class UICadCliente extends javax.swing.JFrame {

    Cliente objCliente = new Cliente();

    /**
     * Creates new form UICadCliente
     */
    public UICadCliente() {
        initComponents();
        jbRelatorio.setEnabled(false);
        jtQuantos.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        bgPossuiCartao = new javax.swing.ButtonGroup();
        jlpDados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jlSexo = new javax.swing.JLabel();
        jrMasculino = new javax.swing.JRadioButton();
        jrFeminino = new javax.swing.JRadioButton();
        jlPossuiCartao = new javax.swing.JLabel();
        jrSim = new javax.swing.JRadioButton();
        jrNao = new javax.swing.JRadioButton();
        jlQuantos = new javax.swing.JLabel();
        jtQuantos = new javax.swing.JTextField();
        jlQual = new javax.swing.JLabel();
        jlpCaixaQual = new javax.swing.JLayeredPane();
        jcVisa = new javax.swing.JCheckBox();
        jcElo = new javax.swing.JCheckBox();
        jcBanriCompras = new javax.swing.JCheckBox();
        jcMasterCard = new javax.swing.JCheckBox();
        jcHiperCard = new javax.swing.JCheckBox();
        jcAmericanExpress = new javax.swing.JCheckBox();
        jlConta = new javax.swing.JLabel();
        jlpCaixaConta = new javax.swing.JLayeredPane();
        jcItau = new javax.swing.JCheckBox();
        jcBanrisul = new javax.swing.JCheckBox();
        jcBradesco = new javax.swing.JCheckBox();
        jcSantander = new javax.swing.JCheckBox();
        jlNomeErro = new javax.swing.JLabel();
        jlQtdErro = new javax.swing.JLabel();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlpDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });

        jlSexo.setText("Sexo");

        bgSexo.add(jrMasculino);
        jrMasculino.setText("Masculino");
        jrMasculino.setActionCommand("Masculino");

        bgSexo.add(jrFeminino);
        jrFeminino.setText("Feminino");
        jrFeminino.setActionCommand("Feminino");

        jlPossuiCartao.setText("Possui Cartão? ");

        bgPossuiCartao.add(jrSim);
        jrSim.setText("Sim");
        jrSim.setActionCommand("Sim");
        jrSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrSimActionPerformed(evt);
            }
        });

        bgPossuiCartao.add(jrNao);
        jrNao.setText("Não");
        jrNao.setActionCommand("Não");
        jrNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrNaoActionPerformed(evt);
            }
        });

        jlQuantos.setText("Quantos?");

        jtQuantos.setText("0");
        jtQuantos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtQuantosFocusLost(evt);
            }
        });

        jlQual.setText("Qual(is)");

        jlpCaixaQual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jcVisa.setText("Visa");

        jcElo.setText("Elo");

        jcBanriCompras.setText("BanriCompras");

        jcMasterCard.setText("MasterCard");

        jcHiperCard.setText("HiperCard");

        jcAmericanExpress.setText("American Express");

        jlpCaixaQual.setLayer(jcVisa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCaixaQual.setLayer(jcElo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCaixaQual.setLayer(jcBanriCompras, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCaixaQual.setLayer(jcMasterCard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCaixaQual.setLayer(jcHiperCard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCaixaQual.setLayer(jcAmericanExpress, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpCaixaQualLayout = new javax.swing.GroupLayout(jlpCaixaQual);
        jlpCaixaQual.setLayout(jlpCaixaQualLayout);
        jlpCaixaQualLayout.setHorizontalGroup(
            jlpCaixaQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpCaixaQualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpCaixaQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcVisa)
                    .addComponent(jcMasterCard))
                .addGap(10, 10, 10)
                .addGroup(jlpCaixaQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcHiperCard)
                    .addComponent(jcElo))
                .addGap(10, 10, 10)
                .addGroup(jlpCaixaQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcBanriCompras)
                    .addComponent(jcAmericanExpress))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpCaixaQualLayout.setVerticalGroup(
            jlpCaixaQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpCaixaQualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpCaixaQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcVisa)
                    .addComponent(jcElo)
                    .addComponent(jcBanriCompras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpCaixaQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcMasterCard)
                    .addComponent(jcHiperCard)
                    .addComponent(jcAmericanExpress))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jlConta.setText("Conta(s)");

        jlpCaixaConta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jcItau.setText("Itaú");

        jcBanrisul.setText("Banrisul");

        jcBradesco.setText("Bradesco");

        jcSantander.setText("Santander");

        jlpCaixaConta.setLayer(jcItau, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCaixaConta.setLayer(jcBanrisul, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCaixaConta.setLayer(jcBradesco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCaixaConta.setLayer(jcSantander, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpCaixaContaLayout = new javax.swing.GroupLayout(jlpCaixaConta);
        jlpCaixaConta.setLayout(jlpCaixaContaLayout);
        jlpCaixaContaLayout.setHorizontalGroup(
            jlpCaixaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpCaixaContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpCaixaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcBanrisul)
                    .addComponent(jcItau))
                .addGap(18, 18, 18)
                .addGroup(jlpCaixaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcBradesco)
                    .addComponent(jcSantander))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpCaixaContaLayout.setVerticalGroup(
            jlpCaixaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpCaixaContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpCaixaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcItau)
                    .addComponent(jcBradesco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpCaixaContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcBanrisul)
                    .addComponent(jcSantander))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jlNomeErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.PNG"))); // NOI18N

        jlQtdErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.PNG"))); // NOI18N

        jlpDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrMasculino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrFeminino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlPossuiCartao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrSim, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrNao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlQuantos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtQuantos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlQual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlpCaixaQual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlConta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlpCaixaConta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNomeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlQtdErro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlSexo)
                        .addGap(18, 18, 18)
                        .addComponent(jrMasculino)
                        .addGap(18, 18, 18)
                        .addComponent(jrFeminino))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addGap(18, 18, 18)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlNomeErro))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jlQuantos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtQuantos))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpDadosLayout.createSequentialGroup()
                                .addComponent(jlPossuiCartao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrSim)))
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jrNao))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jlQtdErro))))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlConta)
                            .addComponent(jlQual))
                        .addGap(33, 33, 33)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlpCaixaQual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlpCaixaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlNome)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlNomeErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25)))
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSexo)
                    .addComponent(jrMasculino)
                    .addComponent(jrFeminino))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPossuiCartao)
                    .addComponent(jrSim)
                    .addComponent(jrNao))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlQuantos)
                    .addComponent(jtQuantos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQtdErro))
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jlQual))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlpCaixaQual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlConta)
                        .addGap(42, 42, 42))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlpCaixaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jlpAcoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbRelatorio.setText("Relatório");
        jbRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelatorioActionPerformed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbRelatorio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jbRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpAcoes)
                    .addComponent(jlpDados))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpDados)
                .addGap(18, 18, 18)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cadastrar() {
        try {
            if (!jtNome.getText().isEmpty()) {
                objCliente.setNome(jtNome.getText());
            } else {
                throw new NumberFormatException("Nome Invalido!");
            }
            if (bgSexo.getSelection() != null) {
                objCliente.setSexo(bgSexo.getSelection().getActionCommand());
            } else {
                throw new NumberFormatException("TU TEM SEXO, VIADO?");
            }
            if (bgPossuiCartao.getSelection() != null) {
                objCliente.setPossuiCartao(bgPossuiCartao.getSelection().getActionCommand());
            } else {
                throw new NumberFormatException("TU TEM CARTÃO, MANO?");
            }
            
            objCliente.setQtdCartao(Integer.parseInt(jtQuantos.getText()));

            ArrayList<String> qualCartao = new ArrayList<>();

            if (jcVisa.isSelected()) {
                qualCartao.add(jcVisa.getText());
            }

            if (jcMasterCard.isSelected()) {
                qualCartao.add(jcMasterCard.getText());
            }

            if (jcElo.isSelected()) {
                qualCartao.add(jcElo.getText());
            }

            if (jcHiperCard.isSelected()) {
                qualCartao.add(jcHiperCard.getText());
            }

            if (jcBanriCompras.isSelected()) {
                qualCartao.add(jcBanriCompras.getText());
            }

            if (jcAmericanExpress.isSelected()) {
                qualCartao.add(jcAmericanExpress.getText());
            }

            ArrayList<String> qualConta = new ArrayList<>();

            if (jcItau.isSelected()) {
                qualConta.add(jcItau.getText());
            }

            if (jcBradesco.isSelected()) {
                qualConta.add(jcBradesco.getText());
            }

            if (jcBanrisul.isSelected()) {
                qualConta.add(jcBanrisul.getText());
            }

            if (jcSantander.isSelected()) {
                qualConta.add(jcSantander.getText());
            }

            objCliente.setQualCartao(qualCartao);
            objCliente.setQualConta(qualConta);

            JOptionPane.showMessageDialog(
                    rootPane,
                    "Cadastrado com sucesso!");

            jbRelatorio.setEnabled(true);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Algum erro aconteceu!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Dados! " + objCliente.toString(),
                    "Relatorio",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            System.out.println("passou aqui");
        }

    }

    private void limpar() {
        jtNome.setText("");
        jtQuantos.setText("");
        jtNome.grabFocus();
        bgSexo.clearSelection();
        bgPossuiCartao.clearSelection();

        jcVisa.setSelected(false);
        jcMasterCard.setSelected(false);
        jcElo.setSelected(false);
        jcHiperCard.setSelected(false);
        jcBanriCompras.setSelected(false);
        jcAmericanExpress.setSelected(false);

        jcItau.setSelected(false);
        jcBradesco.setSelected(false);
        jcBanrisul.setSelected(false);
        jcSantander.setSelected(false);

    }

    private void mostrarRelatorio() {
        JOptionPane.showMessageDialog(rootPane, objCliente.toString());
    }
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelatorioActionPerformed
        mostrarRelatorio();
    }//GEN-LAST:event_jbRelatorioActionPerformed

    private void jrSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrSimActionPerformed
        jtQuantos.setEnabled(true);
    }//GEN-LAST:event_jrSimActionPerformed

    private void jrNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrNaoActionPerformed
        jtQuantos.setEnabled(false);
    }//GEN-LAST:event_jrNaoActionPerformed

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        if (jtNome.getText().isEmpty()) {
            jtNome.setBackground(Color.yellow);
            jtNome.setForeground(Color.red);
            jtNome.setBorder(BorderFactory.createLineBorder(Color.red));
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtQuantosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtQuantosFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtQuantosFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UICadCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPossuiCartao;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbRelatorio;
    private javax.swing.JCheckBox jcAmericanExpress;
    private javax.swing.JCheckBox jcBanriCompras;
    private javax.swing.JCheckBox jcBanrisul;
    private javax.swing.JCheckBox jcBradesco;
    private javax.swing.JCheckBox jcElo;
    private javax.swing.JCheckBox jcHiperCard;
    private javax.swing.JCheckBox jcItau;
    private javax.swing.JCheckBox jcMasterCard;
    private javax.swing.JCheckBox jcSantander;
    private javax.swing.JCheckBox jcVisa;
    private javax.swing.JLabel jlConta;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeErro;
    private javax.swing.JLabel jlPossuiCartao;
    private javax.swing.JLabel jlQtdErro;
    private javax.swing.JLabel jlQual;
    private javax.swing.JLabel jlQuantos;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpCaixaConta;
    private javax.swing.JLayeredPane jlpCaixaQual;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JRadioButton jrFeminino;
    private javax.swing.JRadioButton jrMasculino;
    private javax.swing.JRadioButton jrNao;
    private javax.swing.JRadioButton jrSim;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtQuantos;
    // End of variables declaration//GEN-END:variables
}
