/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.VonparVO;
import servicos.ServicosFactory;
import servicos.VonparServicos;

/**
 *
 * @author André Luiz & Eduardo Gautier
 * @since 03/07/2018
 * @version 1.0 charset
 */
public class UICadVonpar extends javax.swing.JInternalFrame {

    VonparVO vVO = new VonparVO();

    /**
     * Creates new form UICadVonpar
     */
    public UICadVonpar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEmbornavel = new javax.swing.ButtonGroup();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jlpDados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlTipo = new javax.swing.JLabel();
        jlQuantidade = new javax.swing.JLabel();
        jlTamanho = new javax.swing.JLabel();
        jlPreco = new javax.swing.JLabel();
        jlEmbalagemRetornalvel = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtTipo = new javax.swing.JTextField();
        jtQuantidade = new javax.swing.JTextField();
        jtTamanho = new javax.swing.JTextField();
        jrbSim = new javax.swing.JRadioButton();
        jrbNao = new javax.swing.JRadioButton();
        jtPreco = new javax.swing.JTextField();
        jlNomeErro = new javax.swing.JLabel();
        jlTipoErro = new javax.swing.JLabel();
        jlQtdErro = new javax.swing.JLabel();
        jlTamanhoErro = new javax.swing.JLabel();
        jlValorErro = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("CADASTRAR PRODUTO");

        jlpAcoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrar.png"))); // NOI18N
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarKeyPressed(evt);
            }
        });

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jlpDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome");

        jlTipo.setText("Tipo de Bebida");

        jlQuantidade.setText("Quantidade Disponivel");

        jlTamanho.setText("Tamanho da Embalagem");

        jlPreco.setText("Valor de Custo");

        jlEmbalagemRetornalvel.setText("Embalagem Retornavel");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jtTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtTipoFocusLost(evt);
            }
        });
        jtTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtTipoKeyPressed(evt);
            }
        });

        jtQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtQuantidadeFocusLost(evt);
            }
        });
        jtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtQuantidadeKeyPressed(evt);
            }
        });

        jtTamanho.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtTamanhoFocusLost(evt);
            }
        });
        jtTamanho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtTamanhoKeyPressed(evt);
            }
        });

        bgEmbornavel.add(jrbSim);
        jrbSim.setText("Sim");
        jrbSim.setActionCommand("Sim");
        jrbSim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbSimKeyPressed(evt);
            }
        });

        bgEmbornavel.add(jrbNao);
        jrbNao.setText("Não");
        jrbNao.setActionCommand("Não");
        jrbNao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbNaoKeyPressed(evt);
            }
        });

        jtPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPrecoFocusLost(evt);
            }
        });
        jtPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPrecoKeyPressed(evt);
            }
        });

        jlNomeErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N

        jlTipoErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N

        jlQtdErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N

        jlTamanhoErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N

        jlValorErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N

        jlpDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlQuantidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTamanho, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlPreco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlEmbalagemRetornalvel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtTipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtQuantidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtTamanho, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrbSim, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrbNao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtPreco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNomeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTipoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlQtdErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTamanhoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlValorErro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTamanho)
                            .addComponent(jlQuantidade))
                        .addGap(18, 18, 18)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlTamanhoErro))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlQtdErro)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jlpDadosLayout.createSequentialGroup()
                                        .addComponent(jlPreco)
                                        .addGap(64, 64, 64)
                                        .addComponent(jtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jlpDadosLayout.createSequentialGroup()
                                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jlTipo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlNome, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(64, 64, 64)
                                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                            .addComponent(jtNome))))
                                .addGap(18, 18, 18)
                                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNomeErro)
                                    .addComponent(jlTipoErro)
                                    .addComponent(jlValorErro)))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jlEmbalagemRetornalvel)
                                .addGap(24, 24, 24)
                                .addComponent(jrbSim)
                                .addGap(18, 18, 18)
                                .addComponent(jrbNao)))
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlNome)
                        .addComponent(jlNomeErro))
                    .addComponent(jtNome))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTipo)
                    .addComponent(jlTipoErro))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQuantidade)
                    .addComponent(jlQtdErro))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlTamanhoErro))
                    .addComponent(jlTamanho))
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlValorErro)
                            .addComponent(jtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jlPreco)))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmbalagemRetornalvel)
                    .addComponent(jrbSim)
                    .addComponent(jrbNao))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpAcoes)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlpAcoes)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar() {
        try {
            if (!jtNome.getText().isEmpty()) {
                vVO.setNome(jtNome.getText());
            } else {
                throw new NumberFormatException("Nome Inválido!");
            }

            if (!jtTipo.getText().isEmpty()) {
                vVO.setTipoDeBebida(jtTipo.getText());
            } else {
                throw new NumberFormatException("Tipo Inválido!");
            }

            if (!jtQuantidade.getText().isEmpty()) {
                vVO.setQuantidade(Integer.parseInt(jtQuantidade.getText()));
            } else {
                throw new NumberFormatException("Quantidade Inválida!");
            }

            if (!jtTamanho.getText().isEmpty()) {
                vVO.setLitrosGarrafa(Double.parseDouble(jtTamanho.getText()));
            } else {
                throw new NumberFormatException("Tamanho da Embalagem Inválida!");
            }

            if (!jtPreco.getText().isEmpty()) {
                vVO.setPreco(Double.parseDouble(jtPreco.getText()));
            } else {
                throw new NumberFormatException("Preço Inválido!");
            }

            if (bgEmbornavel.getSelection() != null) {
                vVO.setGarrafaRetornavel(bgEmbornavel.getSelection().getActionCommand());
            } else {
                throw new NumberFormatException("A Embalagem é retornável?");
            }

            VonparServicos VS = ServicosFactory.getVonparServicos();
            VS.cadastrarProduto(vVO);

            JOptionPane.showMessageDialog(
                    rootPane,
                    "Cadastro efetuado com sucesso!",
                    "Sistema",
                    JOptionPane.PLAIN_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Algum erro aconteceu!" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpar() {
        jtNome.setText("");
        jtTipo.setText("");
        jtQuantidade.setText("");
        jtTamanho.setText("");
        jtPreco.setText("");
        bgEmbornavel.clearSelection();
        
        jtNome.grabFocus();
    }
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtTipo.grabFocus();
        }
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtTipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTipoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtQuantidade.grabFocus();
        }
    }//GEN-LAST:event_jtTipoKeyPressed

    private void jtQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtQuantidadeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtTamanho.grabFocus();
        }
    }//GEN-LAST:event_jtQuantidadeKeyPressed

    private void jtTamanhoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTamanhoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtPreco.grabFocus();
        }
    }//GEN-LAST:event_jtTamanhoKeyPressed

    private void jtPrecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPrecoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrbSim.grabFocus();
        }
    }//GEN-LAST:event_jtPrecoKeyPressed

    private void jrbSimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbSimKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrar();
            limpar();
        }
    }//GEN-LAST:event_jrbSimKeyPressed

    private void jrbNaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbNaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {   
            cadastrar();
            limpar();
        }
    }//GEN-LAST:event_jrbNaoKeyPressed

    private void jbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrar();
            limpar();
        }
    }//GEN-LAST:event_jbCadastrarKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limpar();
        }
    }//GEN-LAST:event_jbLimparKeyPressed

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        if (jtNome.getText().isEmpty()) {
            jtNome.setBackground(Color.decode("#FFFFF0"));
            jtNome.setBorder(BorderFactory.createLineBorder(Color.red));
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/erro.png")));
        } else {
            jtNome.setBackground(Color.white);
            jtNome.setBorder(BorderFactory.createLineBorder(Color.gray));
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtTipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtTipoFocusLost
        if (jtTipo.getText().isEmpty()) {
            jtTipo.setBackground(Color.decode("#FFFFF0"));
            jtTipo.setBorder(BorderFactory.createLineBorder(Color.red));
            jlTipoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/erro.png")));
        } else {
            jtTipo.setBackground(Color.white);
            jtTipo.setBorder(BorderFactory.createLineBorder(Color.gray));
            jlTipoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtTipoFocusLost

    private void jtQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtQuantidadeFocusLost
        if (jtQuantidade.getText().isEmpty()) {
            jtQuantidade.setBackground(Color.decode("#FFFFF0"));
            jtQuantidade.setBorder(BorderFactory.createLineBorder(Color.red));
            jlQtdErro.setIcon(new ImageIcon(getClass().getResource("/imagens/erro.png")));
        } else {
            jtQuantidade.setBackground(Color.white);
            jtQuantidade.setBorder(BorderFactory.createLineBorder(Color.gray));
            jlQtdErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtQuantidadeFocusLost

    private void jtTamanhoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtTamanhoFocusLost
        if (jtTamanho.getText().isEmpty()) {
            jtTamanho.setBackground(Color.decode("#FFFFF0"));
            jtTamanho.setBorder(BorderFactory.createLineBorder(Color.red));
            jlTamanhoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/erro.png")));
        } else {
            jtTamanho.setBackground(Color.white);
            jtTamanho.setBorder(BorderFactory.createLineBorder(Color.gray));
            jlTamanhoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtTamanhoFocusLost

    private void jtPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPrecoFocusLost
        if (jtPreco.getText().isEmpty()) {
            jtPreco.setBackground(Color.decode("#FFFFF0"));
            jtPreco.setBorder(BorderFactory.createLineBorder(Color.red));
            jlValorErro.setIcon(new ImageIcon(getClass().getResource("/imagens/erro.png")));
        } else {
            jtPreco.setBackground(Color.white);
            jtPreco.setBorder(BorderFactory.createLineBorder(Color.gray));
            jlValorErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtPrecoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEmbornavel;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlEmbalagemRetornalvel;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeErro;
    private javax.swing.JLabel jlPreco;
    private javax.swing.JLabel jlQtdErro;
    private javax.swing.JLabel jlQuantidade;
    private javax.swing.JLabel jlTamanho;
    private javax.swing.JLabel jlTamanhoErro;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JLabel jlTipoErro;
    private javax.swing.JLabel jlValorErro;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JRadioButton jrbNao;
    private javax.swing.JRadioButton jrbSim;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPreco;
    private javax.swing.JTextField jtQuantidade;
    private javax.swing.JTextField jtTamanho;
    private javax.swing.JTextField jtTipo;
    // End of variables declaration//GEN-END:variables
}
