/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.EpisodioVO;
import modelo.SeriadoVO;
import servicos.EpisodioServicos;
import servicos.SeriadoServicos;
import servicos.ServicosFactory;

/**
 * @author Thiago Cury
 * @since 25/04/2014
 * @version 1.0
 */
public class GuiCadEpisodio extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiCadEpisodio
     */
    public GuiCadEpisodio() {
        initComponents();
        /* Chamando o preencherCombo no construtor. 
           Com isso será preenchido todos objetos na JComboBox
           na construção da janela. */
        
        preencherCombo();
        
    }//fecha construtor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlDuracao = new javax.swing.JLabel();
        jlSeriado = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtDuracao = new javax.swing.JTextField();
        jcomboSeriado = new javax.swing.JComboBox();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("cadastro de episódio");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome");
        jLayeredPane1.add(jlNome);
        jlNome.setBounds(30, 40, 60, 14);

        jlDuracao.setText("Duração");
        jLayeredPane1.add(jlDuracao);
        jlDuracao.setBounds(30, 100, 80, 14);

        jlSeriado.setText("Seriado");
        jLayeredPane1.add(jlSeriado);
        jlSeriado.setBounds(30, 170, 80, 14);
        jLayeredPane1.add(jtNome);
        jtNome.setBounds(130, 40, 280, 30);
        jLayeredPane1.add(jtDuracao);
        jtDuracao.setBounds(130, 100, 280, 30);

        jLayeredPane1.add(jcomboSeriado);
        jcomboSeriado.setBounds(130, 150, 280, 60);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jbCadastrar);
        jbCadastrar.setBounds(20, 20, 120, 23);

        jbLimpar.setText("limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jbLimpar);
        jbLimpar.setBounds(170, 20, 117, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Método responsável pelo preenchimento da JComboBox
    private void preencherCombo(){
        try {
          
            SeriadoServicos SS = ServicosFactory.getSeriadoServicos();
            ArrayList<SeriadoVO> s = SS.buscarSeriados();
            
            for (int i = 0; i < s.size(); i++) {
                jcomboSeriado.addItem(s.get(i));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! "+e.getMessage());
        }//fecha catch
    }//fecha método preencherCombo
    
    private void cadastrar(){
        try {
            
            EpisodioVO  e= new EpisodioVO();
            e.setNome(jtNome.getText());
            e.setDuracao(Double.parseDouble(jtDuracao.getText()));
            e.setSeriado((SeriadoVO)jcomboSeriado.getSelectedItem());
            
            EpisodioServicos ES = ServicosFactory.getEpisodioServicos();
            ES.cadastrarEpisodio(e);
            
            JOptionPane.showMessageDialog(
                    this, 
                    "Episódio cadastrado com sucesso!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! "+e.getMessage());
        }//fecha catch
    }//fecha método cadastrar
    
    private void limpar(){
        jtNome.setText(null);
        jtDuracao.setText(null);
        jcomboSeriado.setSelectedIndex(0);
    }//fecha método limpar
    
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JComboBox jcomboSeriado;
    private javax.swing.JLabel jlDuracao;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlSeriado;
    private javax.swing.JTextField jtDuracao;
    private javax.swing.JTextField jtNome;
    // End of variables declaration//GEN-END:variables
}
