/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 * @author Thiago Cury
 * @since 25/04/2014
 * @version 1.0
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAreaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiCadSeriado = new javax.swing.JMenuItem();
        jmiEpisodio = new javax.swing.JMenuItem();
        jmManutencao = new javax.swing.JMenu();
        jmiManSeriado = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmCadastro.setText("cadastro");

        jmiCadSeriado.setText("seriado");
        jmiCadSeriado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadSeriadoActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCadSeriado);

        jmiEpisodio.setText("episodio");
        jmiEpisodio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEpisodioActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiEpisodio);

        jMenuBar1.add(jmCadastro);

        jmManutencao.setText("manutencao");

        jmiManSeriado.setText("seriado");
        jmiManSeriado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManSeriadoActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManSeriado);

        jMenuBar1.add(jmManutencao);

        jmSair.setText("sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirCadEpisodio(){
        GuiCadEpisodio gce = new GuiCadEpisodio();
        jAreaTrabalho.add(gce);
        gce.setVisible(true);
    }//fecha método
    
    private void abrirCadSeriado(){
        GuiCadSeriado gcs = new GuiCadSeriado();
        jAreaTrabalho.add(gcs);
        gcs.setVisible(true);
    }//fecha método
    
    private void abrirManSeriado(){
        GuiManutencaoSeriado gms = new GuiManutencaoSeriado();
        jAreaTrabalho.add(gms);
        gms.setVisible(true);
    }//fecha método
    
    private void jmiCadSeriadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadSeriadoActionPerformed
        abrirCadSeriado();
    }//GEN-LAST:event_jmiCadSeriadoActionPerformed

    private void jmiEpisodioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEpisodioActionPerformed
        abrirCadEpisodio();
    }//GEN-LAST:event_jmiEpisodioActionPerformed

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_jmSairMouseClicked

    private void jmiManSeriadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManSeriadoActionPerformed
        abrirManSeriado();
    }//GEN-LAST:event_jmiManSeriadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaTrabalho;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmManutencao;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmiCadSeriado;
    private javax.swing.JMenuItem jmiEpisodio;
    private javax.swing.JMenuItem jmiManSeriado;
    // End of variables declaration//GEN-END:variables
}
