/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.ClienteVO;
import servicos.ClienteServicos;
import servicos.ServicosFactory;

/**
 *
 * @author André Luiz Alves
 * @since 30/06/2018 10h38
 * @version 3.0 BERG
 */
public class GUICadCliente extends javax.swing.JInternalFrame {

    ClienteVO objCliente = new ClienteVO();
    
    private int validarQtdCartoes = 0;
    /**
     * Creates new form GUICadCliente
     */
    public GUICadCliente() {
        initComponents();
        jbRelatorio.setEnabled(false);
        jtQuantos.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        bgCartao = new javax.swing.ButtonGroup();
        jlpDados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlSexo = new javax.swing.JLabel();
        jlPossuiCartao = new javax.swing.JLabel();
        jlQuantos = new javax.swing.JLabel();
        jlQualCartao = new javax.swing.JLabel();
        jlQualConta = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jrMasculino = new javax.swing.JRadioButton();
        jrFeminino = new javax.swing.JRadioButton();
        jrSim = new javax.swing.JRadioButton();
        jrNao = new javax.swing.JRadioButton();
        jtQuantos = new javax.swing.JTextField();
        jlpQuais = new javax.swing.JLayeredPane();
        jcVisa = new javax.swing.JCheckBox();
        jcElo = new javax.swing.JCheckBox();
        jcBanriCompras = new javax.swing.JCheckBox();
        jcMasterCard = new javax.swing.JCheckBox();
        jcHiperCard = new javax.swing.JCheckBox();
        jcAmericanExpress = new javax.swing.JCheckBox();
        jlpContas = new javax.swing.JLayeredPane();
        jcItau = new javax.swing.JCheckBox();
        jcBradesco = new javax.swing.JCheckBox();
        jcBanrisul = new javax.swing.JCheckBox();
        jcSantander = new javax.swing.JCheckBox();
        jlNomeErro = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbRelatorio = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("CADASTRO DE CLIENTE");

        jlpDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome:");

        jlSexo.setText("Sexo:");

        jlPossuiCartao.setText("Possui Cartão?");

        jlQuantos.setText("Quantos?");

        jlQualCartao.setText("Quais?");

        jlQualConta.setText("Conta(s):");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });

        bgSexo.add(jrMasculino);
        jrMasculino.setText("Masculino");
        jrMasculino.setActionCommand("Masculino");

        bgSexo.add(jrFeminino);
        jrFeminino.setText("Feminino");
        jrFeminino.setActionCommand("Feminino");

        bgCartao.add(jrSim);
        jrSim.setText("Sim");
        jrSim.setActionCommand("Sim");
        jrSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrSimActionPerformed(evt);
            }
        });

        bgCartao.add(jrNao);
        jrNao.setText("Não");
        jrNao.setActionCommand("Não");
        jrNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrNaoActionPerformed(evt);
            }
        });

        jtQuantos.setText("0");
        jtQuantos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtQuantosFocusLost(evt);
            }
        });

        jlpQuais.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jcVisa.setText("Visa");

        jcElo.setText("Elo");

        jcBanriCompras.setText("BanriCompras");

        jcMasterCard.setText("MasterCard");

        jcHiperCard.setText("HiperCard");

        jcAmericanExpress.setText("American Express");

        jlpQuais.setLayer(jcVisa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpQuais.setLayer(jcElo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpQuais.setLayer(jcBanriCompras, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpQuais.setLayer(jcMasterCard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpQuais.setLayer(jcHiperCard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpQuais.setLayer(jcAmericanExpress, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpQuaisLayout = new javax.swing.GroupLayout(jlpQuais);
        jlpQuais.setLayout(jlpQuaisLayout);
        jlpQuaisLayout.setHorizontalGroup(
            jlpQuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpQuaisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jlpQuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcMasterCard)
                    .addComponent(jcVisa))
                .addGap(18, 18, 18)
                .addGroup(jlpQuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcElo)
                    .addComponent(jcHiperCard))
                .addGap(18, 18, 18)
                .addGroup(jlpQuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcBanriCompras)
                    .addComponent(jcAmericanExpress)))
        );
        jlpQuaisLayout.setVerticalGroup(
            jlpQuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpQuaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpQuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcVisa)
                    .addComponent(jcElo)
                    .addComponent(jcBanriCompras))
                .addGap(18, 18, 18)
                .addGroup(jlpQuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcMasterCard)
                    .addComponent(jcHiperCard)
                    .addComponent(jcAmericanExpress))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlpContas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jcItau.setText("Itaú");

        jcBradesco.setText("Bradesco");

        jcBanrisul.setText("Banrisul");

        jcSantander.setText("Santander");

        jlpContas.setLayer(jcItau, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpContas.setLayer(jcBradesco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpContas.setLayer(jcBanrisul, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpContas.setLayer(jcSantander, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpContasLayout = new javax.swing.GroupLayout(jlpContas);
        jlpContas.setLayout(jlpContasLayout);
        jlpContasLayout.setHorizontalGroup(
            jlpContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpContasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcBanrisul)
                    .addComponent(jcItau))
                .addGap(18, 18, 18)
                .addGroup(jlpContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcBradesco)
                    .addComponent(jcSantander))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpContasLayout.setVerticalGroup(
            jlpContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpContasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcItau)
                    .addComponent(jcBradesco))
                .addGap(18, 18, 18)
                .addGroup(jlpContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcBanrisul)
                    .addComponent(jcSantander))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlNomeErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N

        jlpDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlPossuiCartao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlQuantos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlQualCartao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlQualConta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrMasculino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrFeminino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrSim, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrNao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtQuantos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlpQuais, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlpContas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNomeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlLogo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlPossuiCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlQuantos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlQualCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlQualConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlNomeErro))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jrMasculino)
                                .addGap(18, 18, 18)
                                .addComponent(jrFeminino))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jrSim)
                                .addGap(18, 18, 18)
                                .addComponent(jrNao)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlLogo))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtQuantos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlpQuais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlpContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlNome)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNomeErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(20, 20, 20)))
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlSexo)
                            .addComponent(jrMasculino)
                            .addComponent(jrFeminino))
                        .addGap(18, 18, 18)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPossuiCartao)
                            .addComponent(jrSim)
                            .addComponent(jrNao)))
                    .addComponent(jlLogo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlQuantos)
                    .addComponent(jtQuantos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpQuais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQualCartao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQualConta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlpAcoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrar.png"))); // NOI18N
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N
        jbRelatorio.setText("Relatório");
        jbRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelatorioActionPerformed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbRelatorio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLimpar)
                .addGap(65, 65, 65)
                .addComponent(jbRelatorio)
                .addContainerGap())
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpar)
                    .addComponent(jbRelatorio)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpDados)
                    .addComponent(jlpAcoes, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cadastrar() {

        try {
            if (!jtNome.getText().isEmpty()) {
                objCliente.setNome(jtNome.getText());
            } else {
                throw new NumberFormatException("Nome Inválido!");
            }

            if (bgSexo.getSelection() != null) {
                objCliente.setSexo(bgSexo.getSelection().getActionCommand());
            } else {
                throw new NumberFormatException("Informe o Sexo!");
            }

            if (bgCartao.getSelection() != null) {
                objCliente.setPossuiCartao(bgCartao.getSelection().getActionCommand());
            } else {
                throw new NumberFormatException("Possui Cartão?");
            }

            objCliente.setQtdCartoes(Integer.parseInt(jtQuantos.getText()));

            ArrayList<String> qualCartao = new ArrayList<>();

            if (jcVisa.isSelected()) {
                qualCartao.add(jcVisa.getText());
                validarQtdCartoes++;
            }else{
                qualCartao.add("-");
            }

            if (jcElo.isSelected()) {
                qualCartao.add(jcElo.getText());
                validarQtdCartoes++;
            }else{
                qualCartao.add("-");
            }

            if (jcBanriCompras.isSelected()) {
                qualCartao.add(jcBanriCompras.getText());
                validarQtdCartoes++;
            }else{
                qualCartao.add("-");
            }

            if (jcMasterCard.isSelected()) {
                qualCartao.add(jcMasterCard.getText());
                validarQtdCartoes++;
            }else{
                qualCartao.add("-");
            }

            if (jcHiperCard.isSelected()) {
                qualCartao.add(jcHiperCard.getText());
                validarQtdCartoes++;
            }else{
                qualCartao.add("-");
            }

            if (jcAmericanExpress.isSelected()) {
                qualCartao.add(jcAmericanExpress.getText());
                validarQtdCartoes++;
            }else{
                qualCartao.add("-");
            }

            //if para comparar se a quantidade de cartoes selecionada é equivalente a digitada
            if(validarQtdCartoes != Integer.parseInt(jtQuantos.getText())){
                throw new Exception("Quantidade inválida de cartões selecionados!");
            }
            
            ArrayList<String> qualConta = new ArrayList<>();

            if (jcItau.isSelected()) {
                qualConta.add(jcItau.getText());
            }else{
                qualConta.add("-");
            }
            
            objCliente.setQualCartao(qualCartao);

            if (jcBradesco.isSelected()) {
                qualConta.add(jcBradesco.getText());
            }else{
                qualConta.add("-");
            }

            if (jcBanrisul.isSelected()) {
                qualConta.add(jcBanrisul.getText());
            }else{
                qualConta.add("-");
            }

            if (jcSantander.isSelected()) {
                qualConta.add(jcSantander.getText());
            }else{
                qualConta.add("-");
            }

            
            objCliente.setQualConta(qualConta);
            
            //banco
            ClienteServicos CS = ServicosFactory.getClienteServicos();
            CS.cadastrarCliente(objCliente);
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Cadastro efetuado com sucesso!",
                    "Sistema",
                    JOptionPane.PLAIN_MESSAGE);
            
            jbRelatorio.setEnabled(true);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            validarQtdCartoes = 0;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Algum erro aconteceu!" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            validarQtdCartoes = 0;
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Dados: " + objCliente.toString(),
                    "Relatorio",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpar() {
        jtNome.setText("");
        bgSexo.clearSelection();
        bgCartao.clearSelection();
        jtQuantos.setText("0");
        jtQuantos.setEnabled(false);
        //CheckBoxQuais
        jcVisa.setSelected(false);
        jcElo.setSelected(false);
        jcBanriCompras.setSelected(false);
        jcMasterCard.setSelected(false);
        jcHiperCard.setSelected(false);
        jcAmericanExpress.setSelected(false);
        //CheckBoxContas
        jcItau.setSelected(false);
        jcBradesco.setSelected(false);
        jcBanrisul.setSelected(false);
        jcSantander.setSelected(false);
        
        jtNome.grabFocus();
        
    }

    private void mostrarRelatorio() {
        JOptionPane.showMessageDialog(
                rootPane,
                objCliente.toString(),
                "Relatório",
                JOptionPane.PLAIN_MESSAGE);
    }
    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        if (jtNome.getText().isEmpty()) {
            jtNome.setBackground(Color.decode("#FFFFF0"));
            jtNome.setBorder(BorderFactory.createLineBorder(Color.red));
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/erro.png")));
        } else {
            jtNome.setBackground(Color.white);
            jtNome.setBorder(BorderFactory.createLineBorder(Color.black));
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jrSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrSimActionPerformed
        jtQuantos.setEnabled(true);
    }//GEN-LAST:event_jrSimActionPerformed

    private void jrNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrNaoActionPerformed
        jtQuantos.setEnabled(false);
    }//GEN-LAST:event_jrNaoActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelatorioActionPerformed
        mostrarRelatorio();
    }//GEN-LAST:event_jbRelatorioActionPerformed

    private void jtQuantosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtQuantosFocusLost
        int qtd = Integer.parseInt(jtQuantos.getText());
        
        if(qtd >6 || qtd < 0){
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Quantidade Inválida!",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtQuantosFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCartao;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbRelatorio;
    private javax.swing.JCheckBox jcAmericanExpress;
    private javax.swing.JCheckBox jcBanriCompras;
    private javax.swing.JCheckBox jcBanrisul;
    private javax.swing.JCheckBox jcBradesco;
    private javax.swing.JCheckBox jcElo;
    private javax.swing.JCheckBox jcHiperCard;
    private javax.swing.JCheckBox jcItau;
    private javax.swing.JCheckBox jcMasterCard;
    private javax.swing.JCheckBox jcSantander;
    private javax.swing.JCheckBox jcVisa;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeErro;
    private javax.swing.JLabel jlPossuiCartao;
    private javax.swing.JLabel jlQualCartao;
    private javax.swing.JLabel jlQualConta;
    private javax.swing.JLabel jlQuantos;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpContas;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JLayeredPane jlpQuais;
    private javax.swing.JRadioButton jrFeminino;
    private javax.swing.JRadioButton jrMasculino;
    private javax.swing.JRadioButton jrNao;
    private javax.swing.JRadioButton jrSim;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtQuantos;
    // End of variables declaration//GEN-END:variables
}
